<?php


function clarity_charts_node_view($node, $view_mode, $langcode) {

  if ($node->type != 'statistic') return;

  if ($view_mode == 'full') {

    // TODO: determine chart type (based on stat setting?)

    drupal_add_js("https://www.google.com/jsapi");
    drupal_add_js(drupal_get_path('module', 'clarity_charts') . '/clarity_charts.js');

    if (!isset($node->field_datasources['und'])) return;
    foreach($node->field_datasources['und'] as $delta => $datasource) {

      $ds_info = _clarity_datasources_get_datasource($datasource['dsid']);
      if (call_user_func($ds_info->class . '::getDataType') != 'float') continue;

      $node->content["chart-{$datasource['index']}"] = array(
        '#markup' => "<div id='chart-{$datasource['index']}'>chart</div>",
        '#weight' => -10
      );

      drupal_add_js("clarity_charts.push(new ClarityChart('chart-{$datasource['index']}', 'line', {$node->nid}, {$datasource['index']}));", 'inline');

    }

  }


}