<?php


function clarity_charts_node_view($node, $view_mode, $langcode) {

  if ($node->type != 'statistic') return;

  if ($view_mode == 'full') {

    // TODO: determine chart type (based on stat setting?)

    drupal_add_js("https://www.google.com/jsapi");
    drupal_add_js(drupal_get_path('module', 'clarity_charts') . '/clarity_charts.js');

    if (!isset($node->field_datasources['und'])) return;
    foreach($node->field_datasources['und'] as $delta => $datasource) {

      $node->content["chart-$delta"] = array(
        '#markup' => "<div id='chart-$delta'>chart</div>",
        '#weight' => -10
      );

      drupal_add_js("clarity_charts.push(new ClarityChart('chart-$delta', 'line', {$node->nid}, $delta));", 'inline');

    }

  }


}