<?php
/**
 * @file
 * This module implements the core data source for the Clarity package.
 *
 * A data source presents an interface through which stat data can be submitted
 * by users for stats, and edited, deleted, or plotted on charts.
 *
 * Custom versions of this module can be implemented which poll external datasources.
 * By implementing the same hook interface, these custom modules can supply data to
 * charts.
 */

/*
 * Implementation of hook_help
 */
function clarity_multi_term_datasource_help($path, $arg) {

  switch($path) {
    case 'admin/help#clarity_datasource':
      return '<p>' . t("Implements the core data source for the Clarity package.") . '</p>';
      break;
  }

}

function clarity_multi_term_datasource_theme() {

  return array(
    'clarity_multi_term_datasource_table' => array(
      'template' => 'clarity_multi_term_datasource_table',
      'arguments' => array(
        'data' => array()
      )
    ),
    'clarity_multi_term_datasource_table_row' => array(
      'template' => 'clarity_multi_term_datasource_table',
      'arguments' => array(
        'data' => null
      )
    ),

  );

}

function clarity_multi_term_datasource_preprocess_clarity_multi_term_table(&$vars) {

  $vars['row_content'] = '';
  foreach($vars['data'] as $data) {
    $vars['row_content'] .= theme('clarity_single_value_table_row', array('data' => $data));
  }

}


/**
 * Configuration form hook
 */
function clarity_multi_term_datasource_config_form($form, &$form_state) {

}





