<?php
/**
 * @file
 * This module implements the core data source for the Clarity package.
 *
 * A data source presents an interface through which stat data can be submitted
 * by users for stats, and edited, deleted, or plotted on charts.
 *
 * Custom versions of this module can be implemented which poll external datasources.
 * By implementing the same hook interface, these custom modules can supply data to
 * charts.
 */

/*
 * Implementation of hook_help
 */
function clarity_datasource_comment_help($path, $arg) {

  switch($path) {
    case 'admin/help#clarity_datasource_comment':
      return '<p>' . t("Implements the comment data source for the Clarity package.") . '</p>';
      break;
  }

}

/*
 * Implementation of hook_menu
 */
function clarity_datasource_comment_menu() {

  $items = array();

  $items['admin/config/datasources/comment'] = array(
    'title' => t('Clarity Datasource Comment'),
    'description' => t('The commnt datasource for the dashboard'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clarity_datasource_comment_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}


function clarity_datasource_comment_theme() {

  return array(
    'clarity_single_value_table' => array(
      'template' => 'clarity_single_value_table',
      'arguments' => array(
        'data' => array()
      )
    ),
    'clarity_single_value_table_row' => array(
      'template' => 'clarity_single_value_table_row',
      'arguments' => array(
        'data' => null
      )
    ),

  );

}

function clarity_datasource_comment_preprocess_clarity_single_value_table(&$vars) {

  $vars['row_content'] = '';
  foreach($vars['data'] as $data) {
    $vars['row_content'] .= theme('clarity_single_value_table_row', array('data' => $data));
  }

}


/**
 * Configuration form hook
 */
function clarity_datasource_comment_config_form($form, &$form_state) {

}





