<?php

/**
 * hook_menu
 */
function clarity_datasources_menu() {

  $items = array();

  $items['submit-data/%'] = array(
    'title'             => 'Data submission form',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('clarity_datasources_submit_data_form', 1),
    'access arguments'  => array('access content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['datasource'] = array(
    'title'             => 'Datasources',
    'page callback'     => 'clarity_datasources_page',
    'access arguments'  => array('access content'),
    'type'              => MENU_NORMAL_ITEM,
  );


  $items['datasource/wire'] = array(
    'title'             => 'Wire protocol access',
    'page callback'     => 'clarity_datasources_wire',
    'file'              => 'clarity_datasources.wire.inc',
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );


  $items['node/%node/assignments'] = array(
    'title'             => 'Assignments',
    'page callback'     => 'clarity_datasources_display_stat_data',
    'page arguments'    => array(1),
    'access callback'   => 'clarity_datasources_stat_data_access',
    'access arguments'  => array(1, 'administer assignments'),
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 2
  );

  $items['node/%node/datasource-config'] = array(
    'title'             => 'Datasource Configuration',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('clarity_datasources_stat_config_form', 1),
    'access callback'   => 'clarity_datasources_stat_data_access',
    'access arguments'  => array(1, 'administer assignments'),
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 2
  );

  return $items;

}


/**
 * Only show the data tab on statistic nodes for users who have access
 * @param unknown_type $node
 * @param unknown_type $access
 */
function clarity_datasources_stat_data_access($node, $access) {

  if ($node->type != 'statistic') return false;
  return user_access($access);

}


/**
 * List the currently active datasources
 */
function clarity_datasources_page() {

    $datasources = _clarity_datasources_get_datasources();
    $content = '';

    foreach ($datasources as $ds) {
      $content .= "<p>{$ds->label}</p>";
    }

    return $content;

}


/**
 * Implementation of hook_theme
 */
function clarity_datasources_theme() {

  return array(
    'stat_data_table' => array(
      'template' => 'stat_data_table',
      'file' => 'clarity_datasources.templates.inc',
      'arguments' => array(
        'stat_nid' => null,
        'options' => array()
      )
    ),
    'stat_data_table_header' => array(
      'template' => 'stat_data_table_header',
      'file' => 'clarity_datasources.templates.inc',
      'arguments' => array(
        'ds_header_labels' => array()
      )
    ),
    'stat_data_table_row' => array(
      'template' => 'stat_data_table_row',
      'file' => 'clarity_datasources.templates.inc',
      'arguments' => array(
        'assignment' => null,
        'ds_column_content' => array()
      )
    )
  );

}


/**
 * Render the data submission form for the given assignment. Invokes
 * a form render via the datasource for the associated statistic.
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @param unknown_type $assignment_id
 */
function clarity_datasources_submit_data_form($form, &$form_state, $assignment_id) {

  $assignment = assignment_load($assignment_id);

  $stat = node_load($assignment->sid);

  $content = 'Statistic: ' . l($stat->title, 'node/' . $stat->nid);

  $content = t('Please submit data for ') . date('n/d/Y', $assignment->expire_date);
  $form['assignment'] = array (
    '#prefix' => "<div>$content</div>",
    '#type' => 'value',
    '#value' => $assignment
  );

  $form['datasources'] = array('#tree' => 'true');

  foreach ($stat->field_datasources['und'] as $delta => $ds) {

    $ds_info = _clarity_datasources_get_datasource($ds['dsid']);

    $form['datasources'][$delta] = array(
      '#type' => 'fieldset',
      '#tree' => 'true'
    );

    if (isset($ds['label'])) {
      $form['datasources'][$delta]['#title'] = $ds['label'];
    }

    $form['datasources'][$delta]['info'] = array (
      '#type' => 'value',
      '#value' => $ds_info
    );

    $ds = new $ds_info->class;
    $form['datasources'][$delta]['data_fields'] = $ds->getDataFormFields($stat, $delta);

    unset($ds);

  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit'
  );


  return $form;

}


/**
 * Form validation for the submit_data form
 * @param $form
 * @param $form_state
 */
function clarity_datasources_submit_data_form_validate($form, &$form_state) {

  $classes = array();

  foreach($form_state['values']['datasources'] as $delta => $ds_fieldset) {

    if (!isset($classes[$ds_fieldset['info']->class])) {
      $classes[$ds_fieldset['info']->class] = new $ds_fieldset['info']->class;
    }

    $classes[$ds_fieldset['info']->class]->validateDataFormFields("datasources][$delta][data_fields][",
                                                                  $ds_fieldset['data_fields'],
                                                                  $delta);

  }

  foreach($classes as $class) {
    unset($ds);
  }

}


/**
 * Form submission for the submit_data form
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function clarity_datasources_submit_data_form_submit($form, &$form_state) {

  $classes = array();

  foreach($form_state['values']['datasources'] as $delta => $ds_fieldset) {

    if (!isset($classes[$ds_fieldset['info']->class])) {
      $classes[$ds_fieldset['info']->class] = new $ds_fieldset['info']->class;
    }

    $classes[$ds_fieldset['info']->class]->submitDataFormFields($ds_fieldset['data_fields'],
                                                                $form_state['values']['assignment']->aid,
                                                                $delta);

  }

  foreach($classes as $class) {
    unset($ds);
  }

  if (!$form_state['values']['assignment']->complete) {
    // Tell the assignment module that this assignment is complete
    module_invoke('assignment', 'data_submitted', $form_state['values']['assignment']->aid);
    global $user;
    $form_state['redirect'] = "user/{$user->uid}/assignments";
  } else {
    db_update('assignment')
    ->condition('aid', $form_state['values']['assignment']->aid, '=')
    ->fields(array('modified_date' => mktime()))
    ->execute();
    $form_state['redirect'] = "node/{$form_state['values']['assignment']->sid}/assignments";
  }


}


function clarity_datasources_stat_config_form($form, &$form_state, $stat) {

  $ds_info = _clarity_datasources_get_datasources_for_stat($stat->nid);

  $form['stat_nid'] = array (
    '#type' => 'value',
    '#value' => $stat->nid
  );

  $form['datasources'] = array (
    '#type' => 'value',
    '#value' => $ds_info
  );

  foreach($ds_info as $delta => $info) {

    $ds = new $info->class;

    if ($ds instanceof DatasourceStatIfc) {

      $result = db_select('clarity_datasource_stat_config', 'c')
        ->fields('c')
        ->condition('stat_id', $stat->nid, '=')
        ->condition('delta', $delta)
        ->execute()->fetchAssoc();
      $config = unserialize($result['config']);

      $form["datasource-$delta"] = $ds->getStatConfigFormFields($stat);
      $form["datasource-$delta"]['#type'] = 'fieldset';

      $form["datasource-$delta"]['#title'] = '';
      if (isset($stat->field_datasources['und'][$delta]['label'])) {
        $form["datasource-$delta"]['#title'] .= $stat->field_datasources['und'][$delta]['label'] . ' - ';
      }
      $form["datasource-$delta"]['#title'] .= $info->label;

      $form["datasource-$delta"]['#tree'] = true;

      foreach($config as $key => $val) {
        $form["datasource-$delta"][$key]['#default_value'] = $val;
      }

    }

  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit'
  );

  return $form;

}


function clarity_datasources_stat_config_form_validate($form, &$form_state) {

  $validated_classes = array();
  foreach($form['datasources']['#value'] as $delta => $info) {

    if (in_array($info->class, $validated_classes)) continue;

    $ds = new $info->class;
    if ($ds instanceof DatasourceStatIfc) {
      $ds->validateStatConfigForm($form, $form_state);
    }
    unset($ds);
    $validated_classes[] = $info->class;

  }

}

function clarity_datasources_stat_config_form_submit($form, &$form_state) {

  db_delete('clarity_datasource_stat_config')->condition('stat_id', $form['stat_nid']['#value'])->execute();

  foreach($form['datasources']['#value'] as $delta => $info) {

    $config = array();
    foreach($form_state['complete form']["datasource-$delta"] as $key => $val) {
      if ($key[0] != '#') {
        $config[$key] = $val['#value'];
      }
    }

    db_insert('clarity_datasource_stat_config')->fields(array(
      'stat_id' => $form['stat_nid']['#value'],
      'delta' => $delta,
      'config' => serialize($config)
    ))->execute();

  }

}


/**
 * Add a datasource to the index.
 * @param string $module The name of the module responsible for the datasource
 * @param string $class  The class name for the datasource
 * @param string $label  The human-readable label for the datasource
 * @param array $data    An array of data to be stored in the index
 */
function clarity_datasources_create_datasource($module, $class, $label, $data = null) {

  if (!module_exists($module)) {
    watchdog('clarity_datasources',
             'module parameter must be an existing module', null, WATCHDOG_ERROR);
    return;
  }

  if (!is_string($class)) {
    watchdog('clarity_datasources',
             'class parameter must be a string', null, WATCHDOG_ERROR);
    return;
  }

  $result = db_query("SELECT * FROM {clarity_datasource} WHERE module = '$module' and class = '$class'");
  $results = $result->fetchAll();
  if (!empty($results)) {
    watchdog('clarity_datasources',
             "datasource $class already exists for $module", null, WATCHDOG_WARNING);
    return;
  }

  if (!is_string($label)) {
    watchdog('clarity_datasources',
             'label parameter must be a string', null, WATCHDOG_ERROR);
    return;
  }

  $datasource = array(
    'type' => 'clarity_datasource',
    'module' => $module,
    'class' => $class,
    'label' => $label
  );

  if (!is_null($data) && !is_array($data)) {
    watchdog('clarity_datasources',
             'data parameter must be an array if given, setting to null', null, WATCHDOG_WARNING);
    $data = null;
  }

  if (!is_null($data)) $datasource['data'] = $data;

  $obj = (object)$datasource;

  drupal_write_record('clarity_datasource', $obj);

}


/**
 * Remove the datasource associated with the given class from the index.
 */
function clarity_datasources_remove_datasource($class) {

  db_query("DELETE FROM {clarity_datasource} WHERE class = '$class'");

}


/**
 * A callback to display the data for a statistic
 * @param node $stat
 */
function clarity_datasources_display_stat_data($stat) {

  if ($stat->type != 'statistic') return t('No data');

  /*
  $ds_info = _clarity_datasources_get_datasource_for_stat($stat->nid);
  if (!isset($ds_info)) {
    return t('No datasource assigned');
  }
  $data_table = call_user_func($ds_info->class . '::createDataTable', $stat->nid);
  */

  drupal_add_css(drupal_get_path('module', 'clarity_datasources') . '/clarity_datasources.css');

  return theme('stat_data_table', array('stat_nid' => $stat->nid));

}


/*****************************************************************************
 * Database interface                                                        *
 *****************************************************************************/

/**
 * Returns a list of all datasources
 */
function _clarity_datasources_get_datasources() {

  $results = db_query('SELECT * FROM {clarity_datasource}');

  if (!$results->rowCount()) return array();

  foreach ($results as $result) {
    $datasources[] = $result;
  }
  return $datasources;

}


/**
 * Returns the datasource with the given id.
 * @param uint $dsid A datasource id
 */
function _clarity_datasources_get_datasource($ds_id) {

  if (!is_numeric($ds_id)) return null;

  $results = db_query("SELECT * FROM {clarity_datasource} WHERE dsid = $ds_id");
  if (empty($results)) return null;
  foreach ($results as $result) return $result;

}


/**
 * Returns the datasource for the given stat
 * TODO: handle multiple datasources per stat
 * @param uint $stat_id The stat id
 */
function _clarity_datasources_get_datasource_for_stat($stat_id) {

  $stat = node_load($stat_id);
  if (!isset($stat->field_datasource) || !count($stat->field_datasource)) return null;
  return _clarity_datasources_get_datasource($stat->field_datasource['und'][0]['dsid']);

}

function _clarity_datasources_get_datasources_for_stat($stat_id, $objects = false) {

  $stat = node_load($stat_id);
  if (!isset($stat->field_datasources) || !count($stat->field_datasources)) return array();

  $result = array();
  foreach ($stat->field_datasources['und'] as $delta => $item) {
    if ($objects) {
      $result[$delta]['info'] = _clarity_datasources_get_datasource($item['dsid']);
      $result[$delta]['object'] = new $result[$delta]['info']->class;
    } else {
      $result[$delta] = _clarity_datasources_get_datasource($item['dsid']);
    }
  }

  return $result;

}


/*****************************************************************************
 * Assignment Hooks                                                          *
 *****************************************************************************/


function clarity_datasources_form_alter(&$form, &$form_state, $form_id) {

  if (substr($form_id, 0, 15) == 'assignment_form') {

    $datasources = _clarity_datasources_get_datasources_for_stat($form['sid']['#value']);
    $ds_objs = array();
    foreach ($datasources as $delta => $ds_info) {
      if (!isset($ds_objs[$ds_info->class])) $ds_objs[$ds_info->class] = new $ds_info->class;
      if ($ds_objs[$ds_info->class] instanceof DatasourceAssignmentIfc) {
        $ds->assignmentFormFields($form, $form_state, $form_id);
      }
    }

    foreach ($ds_objs as $obj) unset($obj);

  }

}


function clarity_datasources_entity_load($entities, $type) {

  switch($type) {

    case 'assignment':

      // Sort so that we can make one call per datasource
      $ds_sorted = array();
      $ds_aids = array();
      foreach ($entities as $assignment) {
        $datasources = _clarity_datasources_get_datasources_for_stat($assignment->sid);
        foreach ($datasources as $ds_info) {
          if (isset($ds_aids[$ds_info->class]) && in_array($assignment->aid, $ds_aids[$ds_info->class])) continue;
          $ds_aids[$ds_info->class][] = $assignment->aid;
          $ds_sorted[$ds_info->class][] = $assignment;
        }
      }

      foreach($ds_sorted as $class => $entities) {

        $ds = new $class;
        if ($ds instanceof DatasourceAssignmentIfc) {
          $ds->onAssignmentLoad($entities);
        }
        unset($ds);

      }

      break;

    case 'node':

      foreach ($entities as $node) {
        if ($node->type != 'statistic') continue;
        foreach ($node->field_datasources['und'] as $delta => &$item) {
          $result = db_select('clarity_datasource_stat_config', 'c')
            ->fields('c')
            ->condition('stat_id', $node->nid, '=')
            ->condition('delta', $delta)
            ->execute()->fetchAssoc();
          $item['config'] = unserialize($result['config']);
        }
      }

      break;

  }

}


function clarity_datasources_entity_presave($entity, $type) {

  if ($type != 'assignment') return;

  $datasources = _clarity_datasources_get_datasources_for_stat($entity->sid);
  $ds_objs = array();
  foreach ($datasources as $delta => $ds_info) {
    if (!isset($ds_objs[$ds_info->class])) $ds_objs[$ds_info->class] = new $ds_info->class;
    if ($ds_objs[$ds_info->class] instanceof DatasourceAssignmentIfc) {
      $ds->onAssignmentPresave($entity);
    }
  }

  foreach ($ds_objs as $obj) unset($obj);

}


function clarity_datasources_assignment_update($assignment) {

  $datasources = _clarity_datasources_get_datasources_for_stat($assignment->sid);
  $ds_objs = array();
  foreach ($datasources as $delta => $ds_info) {
    if (!isset($ds_objs[$ds_info->class])) $ds_objs[$ds_info->class] = new $ds_info->class;
    if ($ds_objs[$ds_info->class] instanceof DatasourceAssignmentIfc) {
      $ds->onAssignmentUpdate($assignment);
    }
  }

  foreach ($ds_objs as $obj) unset($obj);

}


function clarity_datasources_assignment_insert($assignment) {

  $datasources = _clarity_datasources_get_datasources_for_stat($assignment->sid);
  $ds_objs = array();
  foreach ($datasources as $delta => $ds_info) {
    if (!isset($ds_objs[$ds_info->class])) $ds_objs[$ds_info->class] = new $ds_info->class;
    if ($ds_objs[$ds_info->class] instanceof DatasourceAssignmentIfc) {
      $ds->onAssignmentInsert($assignment);
    }
  }

  foreach ($ds_objs as $obj) unset($obj);

}

/*****************************************************************************
 * Field Hooks                                                               *
 *****************************************************************************/

function clarity_datasources_field_info() {

  return array(
    'clarity_datasource_reference' => array(
      'label' => t('Datasource reference'),
      'description' => t('This field stores a reference to a datasource.'),
      'default_widget' => 'options_select',
      'default_formatter' => 'clarity_datasource_formatter',
    )
  );

}


function clarity_datasources_field_widget_info() {

  return array(
      'clarity_datasource_widget' => array(
          'label' => t('Datasource widget'),
          'field types' => array('clarity_datasource_reference'),
      ),
  );

}


function clarity_datasources_field_widget_form(&$form, &$form_state, $field,
                                               $instance, $langcode, $items, $delta, $element) {

  $field_name = $instance['field_name'];
  $fieldset_info = element_info('fieldset');
  $required = $element['#required'];
  $item =& $items[$delta];

  $opts = clarity_datasources_options_list($field);
  $opts[null] = t('None');

  $element += array('#type' => 'fieldset');

  $element['label'] = array(
    '#title' => t('Label'),
    '#type' => 'textfield',
    '#size' => 20,
    '#default_value' => isset($item['label']) ? $item['label'] : null
  );

  $element['dsid'] = array(
    '#title' => t('Datasource'),
    '#type' => 'select',
    '#options' => $opts,
    '#default_value' => isset($item['dsid']) ? $item['dsid'] : null
  );

  return $element;

}


function clarity_datasources_field_validate($entity_type, $entity, $field,
                                            $instance, $langcode, $items, &$errors) {

  // TODO: If the number of datasources has changed, warn that the data will be blown away

}


function clarity_datasources_field_formatter_info() {

  return array(
      'clarity_datasource_formatter' => array(
          'label' => t('Datasource formatter'),
          'field types' => array('clarity_datasource_reference'),
      ),
  );

}


function clarity_datasources_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();

  switch($display['type']) {
    case 'clarity_datasource_formatter':
      foreach($items as $delta => $item) {
        if (isset($item['dsid'])) {
          $ds = _clarity_datasources_get_datasource($item['dsid']);
          if (is_null($ds)) {
            $element[$delta]['#markup'] = '<span>' . t('None') . '</span>';
          } else {
            $element[$delta]['#markup'] = '';
            if(isset($item['label'])) {
              $element[$delta]['#markup'] = '<span>' . $item['label'] . '</span> - ';
            }
            $element[$delta]['#markup'] .= '<span>' . $ds->label . '</span>';
          }
        }
      }
  }

  return $element;

}


function clarity_datasources_field_widget_info_alter(&$info) {

  $info['options_select']['field types'][] = 'clarity_datasource_reference';
  $info['options_buttons']['field types'][] = 'clarity_datasource_reference';

}


function clarity_datasources_options_list($field) {

  $datasources = _clarity_datasources_get_datasources();
  foreach($datasources as $datasource) {
    $options[$datasource->dsid] = $datasource->label;
  }
  return $options;

}


function clarity_datasources_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element, $error['message']);
}


function clarity_datasources_field_is_empty($item, $field) {
  if ($item['dsid'] == null) return true;
  return false;
}

