<?php
/**
 * @file
 * This module implements the core data source for the Clarity package.
 *
 * A data source presents an interface through which stat data can be submitted
 * by users for stats, and edited, deleted, or plotted on charts.
 *
 * Custom versions of this module can be implemented which poll external datasources.
 * By implementing the same hook interface, these custom modules can supply data to
 * charts.
 */

/*
 * Implementation of hook_help
 */
function clarity_datasource_help($path, $arg) {

  switch($path) {
    case 'admin/help#clarity_datasource':
      return '<p>' . t("Implements the core data source for the Clarity package.") . '</p>';
      break;
  }

}

/*
 * Implementation of hook_menu
 */
function clarity_datasource_menu() {

  $items = array();

  $items['admin/config/datasources/dashboard'] = array(
    'title' => t('Clarity Datasource'),
    'description' => t('The core datasource for the dashboard'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clarity_datasource_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}


/**
 * Configuration form hook
 */
function clarity_datasource_config_form($form, &$form_state) {

}





